apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: juphc-tc_pipeline-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/Qualestrom/juphc-tc_pipeline"
  workspaces:
    - name: pipeline-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
